root: true

ignorePatterns:
  - "**/_site/**"
  - "**/.bundle/**"
  - "**/backstop_data/**"
  - "**/build/**"
  - "**/dist/**"
  - "**/public/**"
  - "**/tmp/**"

parser: "@typescript-eslint/parser"
plugins:
  - "@typescript-eslint"

extends:
  - "eslint:recommended"
  - "airbnb-base"
  - "plugin:@typescript-eslint/eslint-recommended"
  - "plugin:@typescript-eslint/recommended"

env:
  "es2020": true
  "node": true

rules:
  "@typescript-eslint/no-explicit-any": 0
  "eqeqeq": ["error", "always"]
  "no-inner-declarations": 0
  "indent": 0
  "object-shorthand": 0

  "import/no-extraneous-dependencies": 0
  "import/no-unresolved": 0
  "import/extensions": 0
  "max-len": 0
  "no-console": 0

overrides:
  - files: ["*.js", "*.jsx"]
    rules:
      "@typescript-eslint/no-var-requires": 0
      "global-require": 0
  - files: ["tests/*"]
    rules:
      "no-console": 0
  - files: ["web/scripts/*"]
    env:
      "es2020": true
      "node": false
      "browser": true
    rules:
      "no-console": ["error", { allow: ["warn", "error"] }]
  - files: ["visual-tests/*"]
    rules:
      "no-restricted-syntax": 0
      "no-await-in-loop": 0
      "@typescript-eslint/no-non-null-assertion": 0
      "no-continue": 0
