DISABLE:
  - COPYPASTE

DISABLE_LINTERS:
  - JAVASCRIPT_ES
  - JAVASCRIPT_STANDARD
  - JAVASCRIPT_PRETTIER
  - TYPESCRIPT_ES
  - TYPESCRIPT_STANDARD
  - TYPESCRIPT_PRETTIER
  - CSS_SCSS_LINT

# Override default config files
YAML_YAMLLINT_CONFIG_FILE: .yamllint.yml
CSS_STYLELINT_CONFIG_FILE: .stylelintrc.yml
JAVASCRIPT_ES_CONFIG_FILE: .eslintrc.yml
TYPESCRIPT_ES_CONFIG_FILE: .eslintrc.yml
