---
options:
    merge-default-rules: true

rules:
    # disabling
    force-pseudo-nesting:
        - 0
    no-ids:
        - 0

    # customization
    indentation:
        - 2
        -
            size: 4
    property-sort-order:
        - 2
        - order: smacss
...
