---
options:
  merge-default-rules: true

files:
  ignore:
    - node_modules/**/*
    - web/node_modules/**/*

rules:
  # disabling
  force-element-nesting: 0
  no-qualifying-elements: 0

  # customization
  property-sort-order:
    - 2
    - order: smacss
...
