---
# exclude paths
excluded:
    - .build
    - .git
    - build

# rule on/off switching
disabled_rules:
    - todo
    - statement_position
opt_in_rules:
    - attributes
    - closure_end_indentation
    - closure_spacing
    - empty_count
    - explicit_init
    - fatal_error_message
    - first_where
    - force_unwrapping
    - implicit_return
    - implicitly_unwrapped_optional
    - missing_docs
    - nimble_operator
    - no_extension_access_modifier
    - number_separator
    - operator_usage_whitespace
    - overridden_super_call
    - private_outlet
    - prohibited_super_call
    - redundant_nil_coalescing
    - sorted_imports

# rule custizations
trailing_comma:
    mandatory_comma: true
...
