language: node_js

node_js:
  - node # latest
  - 12
  - 11
  - 10
  - 9
  - 8
  - 7
  - 6

addons:
  apt:
    update: true
  homebrew:
    update: true
    brewfile: true

matrix:
  fast_finish: true

  include:
    - os: osx
      language: generic
      osx_image:
        -
        - xcode10.2
        - xcode10.1

install:
  - npm install

before_script:
  - uname -a
  - node --version
  - npm --version

script:
  - npm run build
  - npm run dist
