language: node_js

addons:
  apt:
    update: true
  homebrew:
    update: true
    brewfile: true

node_js:
  - node # latest
  - 12
  - 11
  - 10
  - 9
  - 8
  - 7
  - 6

matrix:
  fast_finish: true
  include:
    - os: osx
      language: generic

install:
  - npm install

before_script:
  - uname -a
  - node --version
  - npm --version

script:
  - npm run build
  - npm run dist
