language: generic

os:
  - linux

addons:
  apt:
    update: true
    packages:
      - build-essential
      - curl
      - ruby
      - ruby-dev
      - pandoc
      - zlib1g
      - zlib1g-dev
      - imagemagick
  homebrew:
    update: true
    brewfile: true

matrix:
  fast_finish: true
  include:
    - { os: osx, if: branch == master }

install:
  - |
    if [ "$(uname -s)" = Linux ]; then
      nvm install node
      nvm use node
    fi

script:
  - make
