language: generic
# sudo: false

os:
  - linux
  - osx

addons:
  apt:
    update: true
    packages:
      - build-essential
      - curl
      - ruby
      - ruby-dev
      - pandoc
      - zlib1g
      - zlib1g-dev
      - imagemagick
      - librsvg2-bin
  homebrew:
    update: true
    brewfile: true

install:
  - |
    if [ "$(uname -s)" = Linux ]; then
      nvm install node
      nvm use node
    fi

script:
  - make
