language: generic

addons:
  apt:
    update: true
    packages:
      - ruby
      - pandoc
      - imagemagick
  homebrew:
    update: true
    brewfile: true

matrix:
  fast_finish: true
  include:
    - { os: linux }
    - { os: osx, osx_image: xcode12, if: branch == master }

install:
  - |
    if [ "$(uname -s)" = Linux ]; then
      nvm install
    elif [ "$(uname -s)" = Darwin ]; then
      nvm unload
      rm -rf "${NVM_DIR}"
    fi
  - travis_wait make bootstrap

script:
  - make lint
  - make build

deploy:
  provider: pages
  skip_cleanup: true
  github_token: $GITHUB_TOKEN
  local_dir: web/public
  target_branch: pages
  if: os = linux
  on:
    branch: master
