language: generic

addons:
  apt:
    update: true
    packages:
      - build-essential
      - curl
      - ruby
      - ruby-dev
      - pandoc
      - zlib1g
      - zlib1g-dev
      - imagemagick
  # homebrew:
  #   update: true
  #   brewfile: true

matrix:
  fast_finish: true
  include:
    - { os: linux }
    - { os: osx, if: branch == master }

install:
  - |
    if [ "$(uname -s)" = Linux ]; then
      nvm install
    elif [ "$(uname -s)" = Darwin ]; then
      time brew update
      time brew bundle
      time brew upgrade node
      nvm use system
    fi

script:
  - make
