language: generic

services:
  - docker

cache:
  directories:
    - web/jekyll/.bundle

addons:
  apt:
    update: true
    packages:
      - ruby
      - pandoc
      - imagemagick
      - build-essential
      - libcairo2-dev
      - libpango1.0-dev
      - libgif-dev
      - librsvg2-dev
  homebrew:
    update: true
    brewfile: true

jobs:
  fast_finish: true
  include:
    - { os: linux }
    - { os: osx, osx_image: xcode11.6, if: branch == master AND type != push }

install:
  - nvm install && nvm use
  - travis_wait 30 make bootstrap

script:
  - make lint
  - make build

deploy:
  provider: pages:git
  edge: true
  cleanup: false
  keep_history: false
  token: $GITHUB_TOKEN
  local_dir: web/public
  target_branch: pages
  on:
    branch: master
