language: node_js

os:
  - linux
  - osx

node_js:
  - node # latest
  - 12
  - 11
  - 10
  - 9
  - 8
  - 7
  - 6

osx_image:
  -
  - xcode10.2
  - xcode10.1
  - xcode10
  - xcode9.4
  - xcode9.3
  - xcode9.2
  - xcode9.1
  - xcode9
  - xcode8.3
  - xcode8
  - xcode7.3
  - xcode6.4

addons:
  apt:
    update: true
  homebrew:
    update: true
    brewfile: true

matrix:
  fast_finish: true

  exclude:
    - { os: linux, osx_image: "" }
    - { os: linux, osx_image: xcode10.2 }
    - { os: linux, osx_image: xcode10.1 }
    - { os: linux, osx_image: xcode10 }
    - { os: linux, osx_image: xcode9.4 }
    - { os: linux, osx_image: xcode9.3 }
    - { os: linux, osx_image: xcode9.2 }
    - { os: linux, osx_image: xcode9.1 }
    - { os: linux, osx_image: xcode9 }
    - { os: linux, osx_image: xcode8.3 }
    - { os: linux, osx_image: xcode8 }
    - { os: linux, osx_image: xcode7.3 }
    - { os: linux, osx_image: xcode6.4 }

install:
  - npm install

before_script:
  - uname -a
  - node --version
  - npm --version

script:
  - npm run build
  - npm run dist
