language: node_js
sudo:
  -
  - false
  - true
  - required
dist:
  - precise
  - trusty
  - xenial

node_js:
  - node
  - 12
  - 11
  - 10
  - 9
  - 8
  - 7
  - 6

install:
  - npm install

script:
  - npm run build
