language: node_js

os:
  - linux
  - osx

sudo: false

services:
  - docker

node_js:
  - # default
  - node # latest
  - 12
  - 11
  - 10
  - 9
  - 8

addons:
  apt:
    update: true
  homebrew:
    update: true
    brewfile: true

matrix:
  fast_finish: true

    # run these jobs on all branches
    - os: osx
      language: generic
      if: branch!=master

    # only run most mac jobs on master
    - &mac
      os: osx
      language: generic
      if: branch=master
    - { <<: *mac, osx_image: xcode11 }
    - { <<: *mac, osx_image: xcode10.2 }
    - { <<: *mac, osx_image: xcode10.1 }
    - { <<: *mac, osx_image: xcode10 }
    - { <<: *mac, osx_image: xcode9.4 }
    - { <<: *mac, osx_image: xcode9.3 }
    - { <<: *mac, osx_image: xcode9.2 }
    - { <<: *mac, osx_image: xcode9.1 }
    - { <<: *mac, osx_image: xcode9 }
    - { <<: *mac, osx_image: xcode8.3 }
    - { <<: *mac, osx_image: xcode8 }
    - { <<: *mac, osx_image: xcode7.3 }
    - { <<: *mac, osx_image: xcode6.4 }

install:
  - npm install

before_script:
  - uname -a
  - node --version
  - npm --version

script:
  - npm run build
  - npm run dist
