#
# This file is part of personal-website which is released under MIT license.
# See file LICENSE.txt or go to https://github.com/matejkosiarcik/personal-website for full license details.
#

---
extends: default

# For all rules
ignore: |
    .git/
    build/
    node_modules/

# rule customization
rules:
    line-length:
        max: 120
...
