version: "{build}"

image:
  - Visual Studio 2017
  # - Visual Studio 2015
  # - Visual Studio 2013

platform:
  # - x86
  - x64
  # - Any CPU

environment:
  matrix:
    - nodejs_version: Current
    - nodejs_version: LTS
    # - nodejs_version: "14"
    # - nodejs_version: "13"
    # - nodejs_version: "12"
    # TODO: include choco versions
    # - nodejs_choco: latest
    # - nodejs_choco: lts

install:
  - ps: Install-Product node $env:nodejs_version $env:platform
  - node --version
  - npm --version

build: script
build_script:
  - ps: echo "placeholder"
