version: "{build}"

image:
  - Visual Studio 2013
  - Previous Visual Studio 2013
  - Visual Studio 2015
  - Previous Visual Studio 2015
  - Visual Studio 2017
  - Previous Visual Studio 2017

platform:
  - x86
  - x64
  - Any CPU

configuration:
  - Debug
  - Release

environment:
  matrix:
    - nodejs_version: "12"
    - nodejs_version: "11"
    - nodejs_version: "10"
    - nodejs_version: "9"
    - nodejs_version: "8"
    - nodejs_version: "7"
    - nodejs_version: "6"

install:
  - ps: Install-Product node $env:nodejs_version $env:platform
  - npm install

build: script
build_script:
  - npm run lint
  - sh: npm run build
  - npm run dist
