version: 2.1

commands:
  install:
    steps:
      - run:
          name: Install dependencies
          command: npm install
  build:
    steps:
      - run:
          name: Build project [dev]
          command: npm run build
      - run:
          name: Build project [prod]
          command: npm run dist

executors:
  node-latest:
    docker:
      - image: circleci/node:latest
  node-lts:
    docker:
      - image: circleci/node:lts

build-template: &build-template
  executor: ${CIRCLE_JOB}
  steps:
    - checkout
    - install
    - build

workflows:
  build:
    jobs:
      - node-latest: { <<: *build-template }
      - node-lts: { <<: *build-template }
