version: 2.1

workflows:
  version: 2
  circleci-build:
    jobs:
      - azlint
      - lint

jobs:
  azlint:
    docker:
      - image: matejkosiarcik/azlint
    steps:
      - checkout
      - run: |
          if [ "$CIRCLE_BRANCH" = main ]; then
            azlint
          else
            azlint --only-changed
          fi

  lint:
    docker:
      - image: debian:stable
    steps:
      - checkout
      - run: |
          apt-get update
          DEBIAN_FRONTEND=noninteractive apt-get install --yes --no-install-recommends build-essential curl ruby ruby-dev zlib1g zlib1g-dev
          curl -sL https://deb.nodesource.com/setup_lts.x | bash - && apt-get install --yes --no-install-recommends nodejs
          npm ci
          npm ci --prefix web
      - run: make lint
