version: 2.1

workflows:
  version: 2
  circleci-build:
    jobs:
      - linux: { matrix: { parameters: { image: [ debian:stable, ubuntu, ubuntu:rolling ]}}}

commands:
  prepare:
    steps:
      - run:
          name: Update system package managers
          command: |
            if command -v apt-get >/dev/null 2>&1; then
              apt-get update
              DEBIAN_FRONTEND=noninteractive apt-get install --yes --no-install-recommends build-essential curl ruby ruby-dev pandoc zlib1g zlib1g-dev imagemagick
              curl -sL https://deb.nodesource.com/setup_14.x | bash - && apt-get install --yes --no-install-recommends nodejs
            fi
  build:
    steps:
      - run: make

jobs:
  linux:
    parameters:
      image:
        type: string
    docker:
      - image: "<< parameters.image >>"
    steps:
      - checkout
      - prepare
      - build
