version: 2.1

commands:
  install:
    steps:
      - run:
          name: Install dependencies
          command: npm install
  build:
    steps:
      - run
          name: Build project in dev config
          command: npm run build
      - run
          name: Build project in prod config
          command: npm run dist

jobs:
  build:
    docker:
      - image: circleci/node:latest
    steps:
      - checkout
      - install
      - build
