version: 2.1

commands:
  install:
    steps:
      - run:
          name: Install dependencies
          command: npm install
  lint:
    steps:
      - run:
          name: Lint source
          command: npm run lint
  build:
    steps:
      - run:
          name: Build project [dev]
          command: npm run build
      - run:
          name: Build project [prod]
          command: npm run dist
  all:
    steps:
      - checkout
      - install
      - lint
      - build

executors:
  node:
    docker:
      - image: circleci/node:<< parameters.tag >>
    parameters:
      tag:
        type: string

jobs:
  node-latest:
    executor: { node, tag: latest }
    steps: [ all ]
  node-lts:
    executor: { node, tag: lts }
    steps: [ all ]

workflows:
  version: 2
  build:
    jobs:
      - node-latest
      - node-lts
