version: 2.1

commands:
  install:
    steps:
      - run:
          name: Install dependencies
          command: npm install
  lint:
    steps:
      - run:
          name: Lint source
          command: npm run lint
  build:
    steps:
      - run:
          name: Build project [dev]
          command: npm run build
      - run:
          name: Build project [prod]
          command: npm run dist
  all:
    steps:
      - checkout
      - install
      - lint
      - build

jobs:
  node-latest:
    image: circleci/node:latest
    steps: [ all ]
  node-lts:
    image: circleci/node:lts
    steps: [ all ]

workflows:
  version: 2
  build:
    jobs:
      - node-latest
      - node-lts
