version: 2.1

commands:
  install:
    steps:
      - run:
          name: Install dependencies
          command: npm install
  build:
    steps:
      - run:
          name: Build project [dev]
          command: npm run build
      - run:
          name: Build project [prod]
          command: npm run dist

jobs:
  build:
    docker:
      - image: circleci/node:latest
    pre-steps:
      - checkout
      - install
    steps:
      - build
