version: 2.1

commands:
  install:
    steps:
      - run:
          name: Install dependencies
          command: npm install
  lint:
    steps:
      - run:
          name: Lint source
          command: npm run lint
  build:
    steps:
      - run:
          name: Build project [dev]
          command: npm run build
      - run:
          name: Build project [prod]
          command: npm run dist

executors:
  node-latest:
    docker:
      - image: circleci/node:latest
  node-lts:
    docker:
      - image: circleci/node:lts

lint-template: &lint-template
  steps:
    - checkout
    - install
    - lint
build-template: &build-template
  steps:
    - checkout
    - install
    - build

jobs:
  lint-latest:
    executor: node-latest
    <<: *lint-template
  lint-lts:
    executor: node-lts
    <<: *lint-template
  build-latest:
    executor: node-latest
    <<: *build-template
  build-lts:
    executor: node-lts
    <<: *build-template

workflows:
  version: 2
  lint:
    jobs:
      - lint-latest
      - lint-lts
  build:
    requires: lint
    jobs:
      - build-latest
      - build-lts
