version: 2.1

commands:
  env_info:
    steps:
      - run:
          name: Print env info
          command: |
            uname -a
            node --version
            npm --version
  install:
    steps:
      - run:
          name: Install dependencies
          command: npm install
  build:
    steps:
      - run:
          name: Build project [dev]
          command: npm run build
      - run:
          name: Build project [prod]
          command: npm run dist
  all:
    steps:
      - checkout
      - env_info
      - install
      - build

jobs:
  node-latest:
    docker: [ image: circleci/node:latest ]
    steps: [ all ]
  node-lts:
    docker: [ image: circleci/node:lts ]
    steps: [ all ]

workflows:
  version: 2
  build:
    jobs:
      - node-latest
      - node-lts
