version: 2.1

commands:
  install:
    - run:
        name: Install dependencies
        command: npm install
  build:
    - run
        name: Build project
        command: |
          npm run build
          npm run dist

jobs:
  build:
    docker:
      - image: circleci/node:latest
    steps:
      - checkout
      - install
      - build
