[build]
  publish = "."
  command = "true"

[[headers]]
  for = "/*"

  [headers.values]
    # TODO: add report-uri or report-to
    # TODO: consider also require-sri-for script style;
    Content-Security-Policy = "default-src 'self' https://*.matejkosiarcik.com; script-src 'self' 'unsafe-inline' https://*.matejkosiarcik.com https://polyfill.io; object-src 'none'; form-action 'none'; frame-src 'none'; frame-ancestors 'none';"

    X-Frame-Options = "DENY"
    X-XSS-Protection = "1; mode=block"
    X-Content-Type-Options = "nosniff"
    Referrer-Policy = "strict-origin-when-cross-origin"

    # disable all
    Feature-Policy = ""
    # Feature-Policy = "accelerometer 'none'; ambient-light-sensor 'none'; autoplay 'none'; camera 'none'; encrypted-media 'none'; fullscreen 'none'; geolocation 'none'; gyroscope 'none'; magnetometer 'none'; microphone 'none'; midi 'none'; payment 'none'; picture-in-picture 'none'; speaker 'none'; sync-xhr 'none'; usb 'none'; vibrate 'none'; vr 'none'"
