name: Create pr for owner

on:  # yamllint disable-line rule:truthy
  push:
    branches:
      - develop

jobs:
  # terminate autopr jobs when new commit is pushed
  autopr-cancel:
    name: Cancel running jobs
    runs-on: ubuntu-latest
    steps:
      - uses: technote-space/auto-cancel-redundant-job@v1
      - name: any steps
        run: echo no more stale autopr

  # creates pr when branch CI succeeds
  autopr:
    name: Auto PR
    runs-on: ubuntu-latest
    steps:
      - name: Wait for status checks
        id: waitforstatuschecks
        uses: WyriHaximus/github-action-wait-for-status@v1
        with:
          ignoreActions: autopr
          checkInterval: 150
        env:
          GITHUB_TOKEN: "${{ secrets.GITHUB_TOKEN }}"
      - name: Checkout project
        uses: actions/checkout@v2
        with:
          path: project
      - name: Create Pull Request
        uses: peter-evans/create-pull-request@v3
        with:
          title: Automatic development PR
          path: project
          assignees: matejkosiarcik
          reviewers: matejkosiarcik
