name: Build and Test

on:
  push:
  pull_request:

jobs:
  # Cancel duplicate jobs: https://github.com/fkirc/skip-duplicate-actions#option-3-cancellation-only
  cancel_duplicates:
    name: Cancel duplicate jobs 🛑
    runs-on: ubuntu-latest
    steps:
      - uses: fkirc/skip-duplicate-actions@master
        with:
          github_token: ${{ secrets.GITHUB_TOKEN }}

  build:
    name: Build 🔧
    id: build
    runs-on: ubuntu-latest
    steps:
      - name: Checkout 🛎️
        uses: actions/checkout@v2.3.4

      - name: Setup nodeJS 🧩
        uses: actions/setup-node@v2.1.5
        with:
          node-version: 14

      - name: Setup ruby 🧩
        uses: ruby/setup-ruby@v1.66.1
        with:
          ruby-version: "2.7"

      - name: Build 🔧
        run: make bootstrap lint build
