name: Build and Deploy

on:  # yamllint disable-line rule:truthy
  push:
    branches:
      - master
      - develop

# TODO: pin exact versions and setup dependabot
jobs:
  build-and-deploy:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout 🛎️
        uses: actions/checkout@v2.3.1

      - name: Build 🔧
        run: |
          cd web
          make bootstrap build

      - name: Deploy 🚀
        uses: JamesIves/github-pages-deploy-action@3.7.1
        with:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
          BRANCH: pages
          FOLDER: web/public
          CLEAN: true
