name: Lint

on:
  push:
  pull_request:
    branches: [master, main]

jobs:
  github-super-linter:
    name: GitHub Super Linter
    runs-on: ubuntu-latest
    steps:
      - name: Checkout 🛎️
        uses: actions/checkout@v2.3.4
        with:
          fetch-depth: 0 # Full git history is needed to get a proper list of changed files

      - name: GitHub Super Linter
        uses: github/super-linter@v3.15.3
        env:
          # global settings
          VALIDATE_ALL_CODEBASE: ${{ github.event_name == 'push' && github.ref == 'refs/heads/master' }}
          DEFAULT_BRANCH: master
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
          LINTER_RULES_PATH: /

          # CSS is linted separately
          VALIDATE_CSS: false
          CSS_FILE_NAME: .stylelintrc.yml

          # JS is linted separately
          JAVASCRIPT_ES_CONFIG_FILE: .eslintrc.yml
          VALIDATE_JAVASCRIPT_ES: false
          VALIDATE_JAVASCRIPT_STANDARD: false
          VALIDATE_TYPESCRIPT_ES: false
          VALIDATE_TYPESCRIPT_STANDARD: false

          # misc
          RUBY_CONFIG_FILE: .rubocop.yml
          VALIDATE_JSCPD: false # TODO: reenable JSCPD

  mega-linter:
    name: Mega-Linter
    runs-on: ubuntu-latest
    steps:
      - name: Checkout 🛎️
        uses: actions/checkout@v2.3.4
        with:
          fetch-depth: 0 # Full git history is needed to get a proper list of changed files

      - name: Mega Linter
        uses: nvuillam/mega-linter@v4.30.0
        env:
          VALIDATE_ALL_CODEBASE: true # ${{ github.event_name == 'push' && github.ref == 'refs/heads/master' }}  # Validates all source when push on master, else just the git diff with master. Override with true if you always want to lint all sources
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
          # Rest of the config is in /.mega-linter.yml
