name: Validate deploy

on:  # yamllint disable-line rule:truthy
  push:
    branches:
      - pages

jobs:
  update-defaults:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout project
        uses: actions/checkout@v2
        with:
          path: project
          ref: master
      - name: Install dependencies
        run: find project
